# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
