# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-09 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160624_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='music_albums_images/default.jpg', null=True, upload_to='music_albums_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MusicianProject')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='songs/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MusicAlbum')),
            ],
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='musician',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillLevel',
        ),
    ]
